version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: alucar_production
    restart: always
    environment:
      MYSQL_DATABASE: alucar_production
      MYSQL_USER: superadmin
      MYSQL_PASSWORD: "204060"
      MYSQL_ROOT_PASSWORD: "204060"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: