version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: alucar_testing
    restart: always
    environment:
      MYSQL_DATABASE: alucar_testing
      MYSQL_USER: testuser
      MYSQL_PASSWORD: "testpassword"
      MYSQL_ROOT_PASSWORD: "testpassword"
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-scripts:/docker-entrypoint-initdb.d

volumes:
  mysql_data: